name: Build

on: [push]

env:
  CI_COMMIT_REF_NAME: ${{ github.ref_name }}
  MODULES_MODULE_TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push images
    steps:
      - uses: actions/checkout@v4

      - uses: haosb/echoserver/setup@main
        with:
          registry: ghcr.io
          registry_login: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the repository name
        id: repo_name
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | cut -d'/' -f2)" >> $GITHUB_OUTPUT

      - uses: deckhouse/modules-actions/build@main
        with:
          module_source: ghcr.io/${{ github.repository_owner }}/modules
          module_name: ${{ steps.repo_name.outputs.REPO_NAME }}
          module_tag: ${{ github.ref_name }}
